POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9sYSIsImlkIjoiNmE1OGFhYmIwZTMyMzYzMmI5YjIwZjFkIiwiaWF0IjoxNzg0MjA0MTc0LCJleHAiOjE3ODQyMDc3NzR9.VkqWM9l7cAGleUS5aKolG20WPFZC6uOQdtLppqitjiA

{
    "title": "title 2",
    "author": "author",
    "url": "url 2",
    "likes": 450,
    "userId": "6a58c9af95129f31de0eccb2"
}
###

DELETE http://localhost:3003/api/blogs/6a58cba295129f31de0eccb5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9sYSIsImlkIjoiNmE1OGFhYmIwZTMyMzYzMmI5YjIwZjFkIiwiaWF0IjoxNzg0MjA2NzkzLCJleHAiOjE3ODQyMTAzOTN9.SuZLwZOIUtgpbT4XA0SMmQMR-1qEUzs7SWfZrp4jX2c
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Ade",
    "name": "AdeolaB",
    "password": "sekret"
}
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Ola",
    "password": "secret"
}